### ISSUE TITLE
getting eroor while colcon build

### ISSUE THREAD

**Issue by Prateek-H-A** [NDHANA94/hyperdog_ros2#11]
$ colcon build 

Starting >>> hyperdog_msgs
Starting >>> hyperdog_launch
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
Finished <<< hyperdog_msgs [0.71s]                                     
Starting >>> hyperdog_ctrl
Starting >>> hyperdog_gazebo_sim
Starting >>> hyperdog_teleop                                  
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
--- stderr: hyperdog_launch                                   
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< hyperdog_launch [1.13s]
Finished <<< hyperdog_gazebo_sim [0.56s]                    
--- stderr: hyperdog_teleop                                 
/home/godofficial/hyperdog_ws/src/hyperdog_teleop/src/hyperdog_teleop_joy.cpp:28:10: fatal error: trajectory_msgs/msg/joint_trajectory.hpp: No such file or directory
   28 | #include "trajectory_msgs/msg/joint_trajectory.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/hyperdog_teleop_joy_node.dir/build.make:76: CMakeFiles/hyperdog_teleop_joy_node.dir/src/hyperdog_teleop_joy.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/hyperdog_teleop_joy_node.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< hyperdog_teleop [0.64s, exited with code 2]
Aborted  <<< hyperdog_ctrl [0.75s]

Summary: 3 packages finished [2.37s]
  1 package failed: hyperdog_teleop
  1 package aborted: hyperdog_ctrl
  2 packages had stderr output: hyperdog_launch hyperdog_teleop

**Comment by NDHANA94** [comment]
Hi! Comment out the `#include "trajectory_msgs/msg/joint_trajectory.hpp"` line in src/hyperdog_teleop_joy.cpp file

**Comment by Prateek-H-A** [comment]
I solved it, just before I saw your reply,
i just added the package "trajectory_msgs" in CMakeList.txt and package.xml

does this effect the flow of code or shall I remove it from those files and comment it??

**Comment by Prateek-H-A** [comment]
and thank you for your reply

**Comment by Prateek-H-A** [comment]
gazebo simulation is working, but the robot slides
does this happen even in physical robot or only is gazebo??

**Comment by NDHANA94** [comment]
Hi!
Yes, robot slides on the ground in gazebo due to some bugs of the ros2-control. Ros2 control has no option to fine tune pid values of joints. But actually the real robot doesn't slide like this.
