### ISSUE TITLE
Port to ESP32?

### ISSUE THREAD

**Issue by samuk** [NDHANA94/hyperdog_ros2#14]
Would you anticipate any issues porting the STMxx code to ESP32?

It might then be possible to run [Wifi-transport](https://github.com/hippo5329/linorobot2_hardware/wiki#why-esp32) so that you could use your main laptop as the compute device when running on cheap hardware such as https://www.aliexpress.com/item/1005004785962170.html

**Comment by NDHANA94** [comment]
Hi!

Since I haven't tried I can't comment on your question. Probably it's possible to use wifi transport.
