### ISSUE TITLE
Question related to hyperdog_ctrl -> cmd_manager -> hyperdog_variables.py

### ISSUE THREAD

**Issue by lukasehr** [NDHANA94/hyperdog_ros2#15]
Hi, I would like to use the gait_generator from Hyperdog for another robot model. However in the python-file hyperdog_variables.py, there are some params that I don't know exactly how they are defined:

1) In Line 95 - 98, there is _L1, _L2 and _L3, I suppose those are the length of the upper_leg, lower_leg and feet?

2) in Line 52-55, there is _length, _width, _min_height, _max_height, are those measured from the ground to the top of the robot or is it only to the centre of gravity?

I would really appreciate an answer!

**Comment by NDHANA94** [comment]
Hi,

_L1 - Hip Link Length
_L2 - Upper Leg Link Length
_L3 - Lower Leg Link Length

_length - distance between back legs origin and front legs origin.
_width - distance between right legs origin and left legs origin.
_min_height - minimum possible height a leg can be along z axis.
_max_height - maximum possible height a leg can be along z axis.

Hope this answer is helpful
