### ISSUE TITLE
Question about sensor use in Hyperdog

### ISSUE THREAD

**Issue by lukasehr** [NDHANA94/hyperdog_ros2#19]
Hey there, I am sorry for asking so many questions...

I just read the papers for Hyperdog. In it you write that the IMU Sensor is used to detect the orientation of the robot. Also there is a current sensor as well as joint encoders. Are those sensors only used in the real Robot (as the microcontroller collects and uses their values) or is it also used in Gazebo?

Also I wanted to ask about the servo motor placement:

In Hyperdog, the servo motors are placed in the main body of the robot. Do you need some kind of conversion to make the joint angles correct? Or is it designed such that for example 10° rotation in the motor equals to 10° rotation in the joint?

Sorry again for the amount of questions, I hope that's okay for you?
Have a nice evening!

**Comment by NDHANA94** [comment]
Hi, 

Yeah, current sensors and imu is only in the real robot. Not yet implemented in simulation. 

And for the second question. No need any converts.

**Comment by lukasehr** [comment]
Alright. Can I ask you how this was done? Are the joint angle encoders mounted on the actual joint or at the actuators? It's a nice way to reduce leg inertia! :)

**Comment by NDHANA94** [comment]
Sensors are embedded to the servo motors
