### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by lukasehr** [NDHANA94/hyperdog_ros2#21]
Hey, in your IEEE SMC-2023 presentation-video, you showed a Plot of the different axis. I think you used the trot_gait_debug method to plot that. Can you explain how you used it? I am trying to use it and get the error: IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed.

**Comment by NDHANA94** [comment]
Hey there, 
I used rqt plot to get those plots.
