### ISSUE TITLE
Gazebo model issues

### ISSUE THREAD

**Issue by Robinroy-peter** [NDHANA94/hyperdog_ros2#3]
gazebo simulation model issues fixed 
1.dynamic friction reduced 
2.joint torque added 
3.robot feet collison points and friction added 
4. gazebo test world file configuration changed

**Comment by lukasehr** [comment]
Sorry for reopening that issue. However I wanted to ask if the model issues have actually been fixed? I tried using Robinroy-peters files but it is still sliding on the ground? I am using Ros2 Humble with Gazebo 11 btw.
