### ISSUE TITLE
I can't drive robot.

### ISSUE THREAD

**Issue by gyiptgyipt** [NDHANA94/hyperdog_ros2#6]

**Comment by Htet-Wai-Yan-HWY** [comment]
Now I can drive do you want to merge?

**Comment by NDHANA94** [comment]
Could you be a bit more specific?

**Comment by gyiptgyipt** [comment]
I launched gazebo spawn and controller_manager one by one but gazebo controller it is the problem of controller param load to gazebo , the joint are quite well with Rviz . but gazebo doesn't move.

**Comment by gyiptgyipt** [comment]
Hello,I loaded all joints (gazebo and JT) and tried to move robot but it still the same than I tried to publish the topic with it's default msg it show the msg_type format error. Do we need to change the "gazebo plugin"?

**Comment by gyiptgyipt** [comment]
Now I can control hyperdog. Thank
